# GPG agent global configuration file
# Suppress GPG agent's debug messages
debug-level none
# Prompt for password each time
default-cache-ttl 0
max-cache-ttl 0
# Use SHA256 for s2k
s2k-digest-algo SHA256
